### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by TomW1605** [theJenix/mailplan#1]
hi not an issue but just wondering if you have keep using this and if it still works.

I have been looking for something like this as outlook has proven unreliable, but I don’t really want to test something this old on my emails just in case.

EDIT: if you don’t use it any more did you find another solution or did the original problem go away?

**Comment by theJenix** [comment]
Hey Tom, thanks for checking out my project!  I last tested it some time last year and it worked great.  It's been a while since I looked at the code, but I don't believe I use any destructive actions (e.g. no deletes, reset read flags, etc) when scanning email.

It was originally built to help me automate downloading attachments that for mail that matched a filter, and I have since used it to generate lists/histograms of senders (to help me clean up my inbox).

If you did decide you wanted to play with it, and end up making any enhancements, file an issue or send over a PR and I'm happy to take a look!

**Comment by TomW1605** [comment]
Hi thanks for the reply. I’m glad to hear it still works, I am not sure why I thought it might not but glad it is. I was planning to modify it to do automatic email sorting. I have had issues with different mail clients filtering rules and I also want some automated processing of some attachments.

I will make a fork and see what I can do and if I make any improvements to the base program, I will make a PR.
